# Generated by Django 3.2.4 on 2021-06-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reveiver',
            new_name='receiver',
        ),
    ]
